services:
  - type: web
    name: popcorn-vidsrc-player
    runtime: node
    plan: free
    region: oregon
    rootDir: .
    buildCommand: npm install --omit=dev --prefix server
    startCommand: npm --prefix server start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: NODE_VERSION
        value: "20"
